// SPDX-License-Identifier: Apache-2.0
// Copyright (C) IURII TRUKHIN 2012-2022, Elena Trukhina 2023-2026. Project and trademarks: Elena Trukhina ZZP.

package openbaoexecutor

import (
	"bytes"
	"errors"
	"text/template"
)

var (
	ErrInvalidProfile        = errors.New("invalid OpenBao executor profile")
	ErrRenderedManifestDrift = errors.New("rendered OpenBao executor manifest drift")
	executorTemplate         = template.Must(template.New("executor").Parse(executorManifestTemplate))
)

// Render returns the exact deterministic 10-object executor bundle. Every
// substituted value has passed DNS-label validation before template execution.
func Render(profile Profile) ([]byte, error) {
	if len(Validate(profile)) != 0 {
		return nil, ErrInvalidProfile
	}
	data := struct {
		ExecutorNamespace      string
		ExecutorServiceAccount string
		PositiveServiceAccount string
		WrongServiceAccount    string
		WrongNamespace         string
		ScopeName              string
	}{
		ExecutorNamespace:      profile.ExecutorIdentity.Namespace,
		ExecutorServiceAccount: profile.ExecutorIdentity.ServiceAccount,
		PositiveServiceAccount: profile.Contract.WorkloadIdentity.ServiceAccount,
		WrongServiceAccount:    profile.NegativeIdentities.WrongServiceAccount.ServiceAccount,
		WrongNamespace:         profile.NegativeIdentities.WrongNamespace.Namespace,
		ScopeName:              profile.Lease.Name,
	}
	var output bytes.Buffer
	if err := executorTemplate.Execute(&output, data); err != nil {
		return nil, ErrInvalidProfile
	}
	return output.Bytes(), nil
}

// VerifyRendered proves byte-for-byte parity with the public renderer. This is
// intentionally stricter than semantic YAML equality so transforms, extra
// fields, preclaimed Leases, and widened RBAC cannot hide in formatting.
func VerifyRendered(profile Profile, manifest []byte) error {
	if err := verifyRenderedSemantics(profile, manifest); err != nil {
		return ErrRenderedManifestDrift
	}
	expected, err := Render(profile)
	if err != nil {
		return err
	}
	if !bytes.Equal(expected, manifest) {
		return ErrRenderedManifestDrift
	}
	return nil
}

const executorManifestTemplate = `# SPDX-License-Identifier: Apache-2.0
# Copyright (C) IURII TRUKHIN 2012-2022, Elena Trukhina 2023-2026.
# Project and trademarks: Elena Trukhina ZZP.
# Code generated by cloudring-openbao; DO NOT EDIT.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{.ExecutorServiceAccount}}'
  namespace: '{{.ExecutorNamespace}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{.WrongServiceAccount}}'
  namespace: '{{.ExecutorNamespace}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{.PositiveServiceAccount}}'
  namespace: '{{.WrongNamespace}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
automountServiceAccountToken: false
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: '{{.ScopeName}}'
  namespace: '{{.ExecutorNamespace}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{.ScopeName}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - selfsubjectreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{.ScopeName}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{.ScopeName}}'
subjects:
  - kind: ServiceAccount
    name: '{{.ExecutorServiceAccount}}'
    namespace: '{{.ExecutorNamespace}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{.ScopeName}}'
  namespace: '{{.ExecutorNamespace}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - '{{.ScopeName}}'
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    resourceNames:
      - '{{.ExecutorServiceAccount}}'
      - '{{.PositiveServiceAccount}}'
      - '{{.WrongServiceAccount}}'
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    resourceNames:
      - '{{.PositiveServiceAccount}}'
      - '{{.WrongServiceAccount}}'
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{.ScopeName}}'
  namespace: '{{.ExecutorNamespace}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{.ScopeName}}'
subjects:
  - kind: ServiceAccount
    name: '{{.ExecutorServiceAccount}}'
    namespace: '{{.ExecutorNamespace}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{.ScopeName}}'
  namespace: '{{.WrongNamespace}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    resourceNames:
      - '{{.PositiveServiceAccount}}'
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    resourceNames:
      - '{{.PositiveServiceAccount}}'
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{.ScopeName}}'
  namespace: '{{.WrongNamespace}}'
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{.ScopeName}}'
subjects:
  - kind: ServiceAccount
    name: '{{.ExecutorServiceAccount}}'
    namespace: '{{.ExecutorNamespace}}'
`
