# SPDX-License-Identifier: Apache-2.0
# Copyright (C) IURII TRUKHIN 2012-2022, Elena Trukhina 2023-2026. Project and trademarks: Elena Trukhina ZZP.

apiVersion: v1
kind: Namespace
metadata:
  name: openbao
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
    cloudring.org/openbao-client: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/part-of: cloudring-secret-manager
    cloudring.org/openbao-client: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
